# ============================================================================
# Project X
# Storage Package
# ============================================================================

from storage.bootstrap import (
    bootstrap_config_dir,
    bootstrap_config_path,
    bootstrap_profile_dir,
)
from storage.exceptions import (
    DataDirectoryNotConfiguredError,
    DataDirectoryValidationError,
    InitializationError,
    InvalidDataDirectoryError,
    MigrationError,
    StorageError,
)
from storage.layout import (
    DATA_ROOT_MARKER_NAME,
    DATA_SUBDIR_CACHE,
    DATA_SUBDIR_CONFIG,
    DATA_SUBDIR_DATABASES,
    DATA_SUBDIR_EXPORTS,
    DATA_SUBDIR_HAJOK,
    DATA_SUBDIR_LOGS,
    DEFAULT_DATA_DIRECTORY_NAME,
    STANDARD_DATA_SUBDIRS,
)
from storage.legacy import (
    LegacyDataInventory,
    collect_legacy_inventory,
    ensure_legacy_data_layout,
    legacy_config_root,
    legacy_data_exists,
    legacy_data_root,
    legacy_logs_root,
    legacy_path_for_subdir,
)
from storage.migration import DataMigrationService, MigrationResult, build_migration_copy_plan
from storage.migration_state import MigrationPhase, MigrationState, MigrationStateStore
from storage.data_root_initialization import (
    DataRootInitializationResult,
    DataRootInitializationService,
)
from storage.data_root_validation import (
    DataRootValidationResult,
    DataRootValidationService,
    ValidationSeverity,
)
from storage.manager import (
    DataDirectoryValidationResult,
    configured_data_root,
    data_root,
    data_subdirectory,
    default_data_directory,
    ensure_active_storage_layout,
    ensure_data_layout,
    validate_data_directory,
    validate_data_directory_or_raise,
)
from storage.marker import (
    ensure_marker,
    find_marked_data_root,
    is_valid_data_root,
    read_marker,
    require_marked_data_root,
)
from storage.resolver import (
    ResolvedDataRoot,
    StorageMode,
    active_cache_path,
    active_config_path,
    active_data_path,
    active_database_path,
    active_export_path,
    active_log_path,
    assert_marker_authority,
    ensure_active_layout,
    marked_data_root_for,
    requires_data_root_setup,
    resolve_data_root,
)

__all__ = [
    "DATA_ROOT_MARKER_NAME",
    "DATA_SUBDIR_CACHE",
    "DATA_SUBDIR_CONFIG",
    "DATA_SUBDIR_DATABASES",
    "DATA_SUBDIR_EXPORTS",
    "DATA_SUBDIR_HAJOK",
    "DATA_SUBDIR_LOGS",
    "DEFAULT_DATA_DIRECTORY_NAME",
    "DataDirectoryNotConfiguredError",
    "DataDirectoryValidationError",
    "DataDirectoryValidationResult",
    "DataRootInitializationResult",
    "DataRootInitializationService",
    "DataRootValidationResult",
    "DataRootValidationService",
    "ValidationSeverity",
    "InvalidDataDirectoryError",
    "InitializationError",
    "LegacyDataInventory",
    "MigrationError",
    "MigrationPhase",
    "MigrationResult",
    "MigrationState",
    "MigrationStateStore",
    "ResolvedDataRoot",
    "STANDARD_DATA_SUBDIRS",
    "StorageError",
    "StorageMode",
    "active_cache_path",
    "active_config_path",
    "active_data_path",
    "active_database_path",
    "active_export_path",
    "active_log_path",
    "assert_marker_authority",
    "bootstrap_config_dir",
    "bootstrap_config_path",
    "bootstrap_profile_dir",
    "build_migration_copy_plan",
    "collect_legacy_inventory",
    "configured_data_root",
    "data_root",
    "data_subdirectory",
    "default_data_directory",
    "DataMigrationService",
    "ensure_active_layout",
    "ensure_active_storage_layout",
    "ensure_data_layout",
    "ensure_legacy_data_layout",
    "ensure_marker",
    "find_marked_data_root",
    "is_valid_data_root",
    "legacy_config_root",
    "legacy_data_exists",
    "legacy_data_root",
    "legacy_logs_root",
    "legacy_path_for_subdir",
    "marked_data_root_for",
    "read_marker",
    "require_marked_data_root",
    "requires_data_root_setup",
    "resolve_data_root",
    "validate_data_directory",
    "validate_data_directory_or_raise",
]
